#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/asus/X00TD

PRODUCT_COPY_FILES += \
    vendor/asus/X00TD/proprietary/product/etc/permissions/qti_fingerprint_interface.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/qti_fingerprint_interface.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_workspaceFile.qwsp \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_workspaceFile.qwsp \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/gc5025_ofilm_13m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/gc5025_ofilm_13m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/gc5025_ofilm_16m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/gc5025_ofilm_16m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/hi1333_ofilm_13m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hi1333_ofilm_13m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/hi556_holitech_13m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hi556_holitech_13m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/hi556_holitech_16m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hi556_holitech_16m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/hi846_kingcome_front_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hi846_kingcome_front_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/hi846_tsp_front_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hi846_tsp_front_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/ov13855_chicony_rear_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13855_chicony_rear_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/ov13855_holitech_13m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13855_holitech_13m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/ov16880_qtech_front_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov16880_qtech_front_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/ov16885_holitech_16m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov16885_holitech_16m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/ov16885_ofilm_16m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov16885_ofilm_16m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/ov8856_chicony_front_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov8856_chicony_front_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/asus/X00TD/proprietary/vendor/firmware/a512_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/a512_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/a512_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/a512_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.elf \
    vendor/asus/X00TD/proprietary/vendor/firmware/a512_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/a530_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_gpmu.fw2 \
    vendor/asus/X00TD/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/asus/X00TD/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/asus/X00TD/proprietary/vendor/firmware/apbtfw10.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/apbtfw10.tlv \
    vendor/asus/X00TD/proprietary/vendor/firmware/apbtfw11.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/apbtfw11.tlv \
    vendor/asus/X00TD/proprietary/vendor/firmware/apnv10.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/apnv10.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/apnv11.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/apnv11.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.102:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.102 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.104:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.104 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.105:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.105 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.106:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.106 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.107:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.107 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.108:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.108 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.109:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.109 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b09 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b0a:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b0a \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b0b:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b0b \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b0d:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b0d \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b0e:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b0e \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b0f:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b0f \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b14 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b30:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b30 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b31:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b31 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b32:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b32 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b33:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b33 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b34:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b34 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b35:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b35 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b36:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b36 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b37:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b37 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b08 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b09 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b11 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b14 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b16 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b18 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b19 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b20 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b22:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b22 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b24:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b24 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b26:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b26 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b28:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b28 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b29:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b29 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b09 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b11 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b13 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b15 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b16 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b18 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b20 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/crbtfw11.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/crbtfw11.tlv \
    vendor/asus/X00TD/proprietary/vendor/firmware/crbtfw20.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/crbtfw20.tlv \
    vendor/asus/X00TD/proprietary/vendor/firmware/crbtfw21.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/crbtfw21.tlv \
    vendor/asus/X00TD/proprietary/vendor/firmware/crnv11.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crnv11.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/crnv20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crnv20.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/crnv21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crnv21.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/data.msc:$(TARGET_COPY_OUT_VENDOR)/firmware/data.msc \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/hyp.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/hyp.mbn \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/mba.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mba.mbn \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b08 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b09 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b10 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b11 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b12 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b13 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b14 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b16 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b17 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b18 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b20 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b21:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b21 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b22:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b22 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b23:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b23 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b24:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b24 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b25:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b25 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b26:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b26 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b27:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b27 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b28:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b28 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/modemuw.jsn:$(TARGET_COPY_OUT_VENDOR)/firmware/modemuw.jsn \
    vendor/asus/X00TD/proprietary/vendor/firmware/novatek_ts_fw_dj.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_dj.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/novatek_ts_fw_txd.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_txd.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/pmic.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/pmic.elf \
    vendor/asus/X00TD/proprietary/vendor/firmware/qdsp6m.qdb:$(TARGET_COPY_OUT_VENDOR)/firmware/qdsp6m.qdb \
    vendor/asus/X00TD/proprietary/vendor/firmware/rpm.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/rpm.mbn \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/asus/X00TD/proprietary/vendor/firmware/venus.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/venus.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/venus.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/venus.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/venus.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/venus.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/wlanmdsp.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/wlanmdsp.mbn \
    vendor/asus/X00TD/proprietary/vendor/firmware/xbl.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/xbl.elf

PRODUCT_PACKAGES += \
    sensors.ssc \
    vendor.qti.hardware.fingerprint@1.0 \
    libactuator_hi1333_ofilm_dw9714v \
    libactuator_ov13855_chicony_rear_s2034 \
    libactuator_ov13855_holitech_fp5510a \
    libactuator_ov16880_qtech_rear_dw9714a \
    libactuator_ov16885_holitech_16m_fp5510a \
    libactuator_ov16885_ofilm_16m_dw9714v \
    libadsp_hvx_callback_skel \
    libadsp_hvx_stub \
    libc++_shared \
    libchromatix_gc5025_ofilm_13m_common \
    libchromatix_gc5025_ofilm_13m_cpp_ds_chromatix \
    libchromatix_gc5025_ofilm_13m_cpp_hfr_120 \
    libchromatix_gc5025_ofilm_13m_cpp_hfr_60 \
    libchromatix_gc5025_ofilm_13m_cpp_hfr_90 \
    libchromatix_gc5025_ofilm_13m_cpp_liveshot \
    libchromatix_gc5025_ofilm_13m_cpp_preview \
    libchromatix_gc5025_ofilm_13m_cpp_snapshot \
    libchromatix_gc5025_ofilm_13m_cpp_us_chromatix \
    libchromatix_gc5025_ofilm_13m_cpp_video \
    libchromatix_gc5025_ofilm_13m_cpp_video_full \
    libchromatix_gc5025_ofilm_13m_default_preview_bu64297 \
    libchromatix_gc5025_ofilm_13m_default_video \
    libchromatix_gc5025_ofilm_13m_default_video_bu64297 \
    libchromatix_gc5025_ofilm_13m_hfr_120 \
    libchromatix_gc5025_ofilm_13m_hfr_120_bu64297 \
    libchromatix_gc5025_ofilm_13m_hfr_60 \
    libchromatix_gc5025_ofilm_13m_hfr_60_bu64297 \
    libchromatix_gc5025_ofilm_13m_hfr_90 \
    libchromatix_gc5025_ofilm_13m_hfr_90_bu64297 \
    libchromatix_gc5025_ofilm_13m_postproc \
    libchromatix_gc5025_ofilm_13m_preview \
    libchromatix_gc5025_ofilm_13m_snapshot \
    libchromatix_gc5025_ofilm_13m_video_full \
    libchromatix_gc5025_ofilm_13m_zsl_preview_bu64297 \
    libchromatix_gc5025_ofilm_13m_zsl_video_bu64297 \
    libchromatix_gc5025_ofilm_16m_common \
    libchromatix_gc5025_ofilm_16m_cpp_ds_chromatix \
    libchromatix_gc5025_ofilm_16m_cpp_hfr_120 \
    libchromatix_gc5025_ofilm_16m_cpp_hfr_60 \
    libchromatix_gc5025_ofilm_16m_cpp_hfr_90 \
    libchromatix_gc5025_ofilm_16m_cpp_liveshot \
    libchromatix_gc5025_ofilm_16m_cpp_preview \
    libchromatix_gc5025_ofilm_16m_cpp_snapshot \
    libchromatix_gc5025_ofilm_16m_cpp_us_chromatix \
    libchromatix_gc5025_ofilm_16m_cpp_video \
    libchromatix_gc5025_ofilm_16m_cpp_video_full \
    libchromatix_gc5025_ofilm_16m_default_preview_bu64297 \
    libchromatix_gc5025_ofilm_16m_default_video \
    libchromatix_gc5025_ofilm_16m_default_video_bu64297 \
    libchromatix_gc5025_ofilm_16m_hfr_120 \
    libchromatix_gc5025_ofilm_16m_hfr_120_bu64297 \
    libchromatix_gc5025_ofilm_16m_hfr_60 \
    libchromatix_gc5025_ofilm_16m_hfr_60_bu64297 \
    libchromatix_gc5025_ofilm_16m_hfr_90 \
    libchromatix_gc5025_ofilm_16m_hfr_90_bu64297 \
    libchromatix_gc5025_ofilm_16m_postproc \
    libchromatix_gc5025_ofilm_16m_preview \
    libchromatix_gc5025_ofilm_16m_snapshot \
    libchromatix_gc5025_ofilm_16m_video_full \
    libchromatix_gc5025_ofilm_16m_zsl_preview_bu64297 \
    libchromatix_gc5025_ofilm_16m_zsl_video_bu64297 \
    libchromatix_hi1333_ofilm_13m_common \
    libchromatix_hi1333_ofilm_13m_cpp_ds_chromatix \
    libchromatix_hi1333_ofilm_13m_cpp_hfr_120 \
    libchromatix_hi1333_ofilm_13m_cpp_hfr_60 \
    libchromatix_hi1333_ofilm_13m_cpp_hfr_90 \
    libchromatix_hi1333_ofilm_13m_cpp_liveshot \
    libchromatix_hi1333_ofilm_13m_cpp_preview \
    libchromatix_hi1333_ofilm_13m_cpp_snapshot \
    libchromatix_hi1333_ofilm_13m_cpp_us_chromatix \
    libchromatix_hi1333_ofilm_13m_cpp_video \
    libchromatix_hi1333_ofilm_13m_cpp_video_full \
    libchromatix_hi1333_ofilm_13m_default_preview_bu64297 \
    libchromatix_hi1333_ofilm_13m_default_video \
    libchromatix_hi1333_ofilm_13m_default_video_bu64297 \
    libchromatix_hi1333_ofilm_13m_eis_video_bu64297 \
    libchromatix_hi1333_ofilm_13m_hdr \
    libchromatix_hi1333_ofilm_13m_hdr_cpp \
    libchromatix_hi1333_ofilm_13m_hdr_video_3a \
    libchromatix_hi1333_ofilm_13m_hfr_120 \
    libchromatix_hi1333_ofilm_13m_hfr_120_bu64297 \
    libchromatix_hi1333_ofilm_13m_hfr_60 \
    libchromatix_hi1333_ofilm_13m_hfr_60_bu64297 \
    libchromatix_hi1333_ofilm_13m_hfr_90 \
    libchromatix_hi1333_ofilm_13m_hfr_90_bu64297 \
    libchromatix_hi1333_ofilm_13m_postproc \
    libchromatix_hi1333_ofilm_13m_preview \
    libchromatix_hi1333_ofilm_13m_snapshot \
    libchromatix_hi1333_ofilm_13m_video_full \
    libchromatix_hi1333_ofilm_13m_zsl_preview_bu64297 \
    libchromatix_hi1333_ofilm_13m_zsl_video_bu64297 \
    libchromatix_hi556_holitech_13m_a3_default_preview \
    libchromatix_hi556_holitech_13m_a3_default_video \
    libchromatix_hi556_holitech_13m_a3_hfr_120 \
    libchromatix_hi556_holitech_13m_a3_hfr_60 \
    libchromatix_hi556_holitech_13m_a3_hfr_90 \
    libchromatix_hi556_holitech_13m_common \
    libchromatix_hi556_holitech_13m_cpp_ds_chromatix \
    libchromatix_hi556_holitech_13m_cpp_hfr_120 \
    libchromatix_hi556_holitech_13m_cpp_hfr_60 \
    libchromatix_hi556_holitech_13m_cpp_hfr_90 \
    libchromatix_hi556_holitech_13m_cpp_liveshot \
    libchromatix_hi556_holitech_13m_cpp_preview \
    libchromatix_hi556_holitech_13m_cpp_snapshot \
    libchromatix_hi556_holitech_13m_cpp_us_chromatix \
    libchromatix_hi556_holitech_13m_cpp_video \
    libchromatix_hi556_holitech_13m_cpp_video_full \
    libchromatix_hi556_holitech_13m_default_video \
    libchromatix_hi556_holitech_13m_hfr_120 \
    libchromatix_hi556_holitech_13m_hfr_60 \
    libchromatix_hi556_holitech_13m_hfr_90 \
    libchromatix_hi556_holitech_13m_postproc \
    libchromatix_hi556_holitech_13m_preview \
    libchromatix_hi556_holitech_13m_snapshot \
    libchromatix_hi556_holitech_13m_video_full \
    libchromatix_hi556_holitech_13m_zsl_preview \
    libchromatix_hi556_holitech_13m_zsl_video \
    libchromatix_hi556_holitech_16m_a3_default_preview \
    libchromatix_hi556_holitech_16m_a3_default_video \
    libchromatix_hi556_holitech_16m_a3_hfr_120 \
    libchromatix_hi556_holitech_16m_a3_hfr_60 \
    libchromatix_hi556_holitech_16m_a3_hfr_90 \
    libchromatix_hi556_holitech_16m_common \
    libchromatix_hi556_holitech_16m_cpp_ds_chromatix \
    libchromatix_hi556_holitech_16m_cpp_hfr_120 \
    libchromatix_hi556_holitech_16m_cpp_hfr_60 \
    libchromatix_hi556_holitech_16m_cpp_hfr_90 \
    libchromatix_hi556_holitech_16m_cpp_liveshot \
    libchromatix_hi556_holitech_16m_cpp_preview \
    libchromatix_hi556_holitech_16m_cpp_snapshot \
    libchromatix_hi556_holitech_16m_cpp_us_chromatix \
    libchromatix_hi556_holitech_16m_cpp_video \
    libchromatix_hi556_holitech_16m_cpp_video_full \
    libchromatix_hi556_holitech_16m_default_video \
    libchromatix_hi556_holitech_16m_hfr_120 \
    libchromatix_hi556_holitech_16m_hfr_60 \
    libchromatix_hi556_holitech_16m_hfr_90 \
    libchromatix_hi556_holitech_16m_postproc \
    libchromatix_hi556_holitech_16m_preview \
    libchromatix_hi556_holitech_16m_snapshot \
    libchromatix_hi556_holitech_16m_video_full \
    libchromatix_hi556_holitech_16m_zsl_preview \
    libchromatix_hi556_holitech_16m_zsl_video \
    libchromatix_hi846_kingcome_front_a3_default_preview \
    libchromatix_hi846_kingcome_front_a3_default_video \
    libchromatix_hi846_kingcome_front_a3_hfr_120 \
    libchromatix_hi846_kingcome_front_a3_hfr_60 \
    libchromatix_hi846_kingcome_front_a3_hfr_90 \
    libchromatix_hi846_kingcome_front_common \
    libchromatix_hi846_kingcome_front_cpp_ds_chromatix \
    libchromatix_hi846_kingcome_front_cpp_hfr_120 \
    libchromatix_hi846_kingcome_front_cpp_hfr_60 \
    libchromatix_hi846_kingcome_front_cpp_hfr_90 \
    libchromatix_hi846_kingcome_front_cpp_liveshot \
    libchromatix_hi846_kingcome_front_cpp_preview \
    libchromatix_hi846_kingcome_front_cpp_snapshot \
    libchromatix_hi846_kingcome_front_cpp_us_chromatix \
    libchromatix_hi846_kingcome_front_cpp_video \
    libchromatix_hi846_kingcome_front_default_video \
    libchromatix_hi846_kingcome_front_hfr_120 \
    libchromatix_hi846_kingcome_front_hfr_60 \
    libchromatix_hi846_kingcome_front_hfr_90 \
    libchromatix_hi846_kingcome_front_liveshot \
    libchromatix_hi846_kingcome_front_postproc \
    libchromatix_hi846_kingcome_front_preview \
    libchromatix_hi846_kingcome_front_snapshot \
    libchromatix_hi846_kingcome_front_zsl_preview \
    libchromatix_hi846_kingcome_front_zsl_video \
    libchromatix_hi846_tsp_front_a3_default_preview \
    libchromatix_hi846_tsp_front_a3_default_video \
    libchromatix_hi846_tsp_front_a3_hfr_120 \
    libchromatix_hi846_tsp_front_a3_hfr_60 \
    libchromatix_hi846_tsp_front_a3_hfr_90 \
    libchromatix_hi846_tsp_front_common \
    libchromatix_hi846_tsp_front_cpp_ds_chromatix \
    libchromatix_hi846_tsp_front_cpp_hfr_120 \
    libchromatix_hi846_tsp_front_cpp_hfr_60 \
    libchromatix_hi846_tsp_front_cpp_hfr_90 \
    libchromatix_hi846_tsp_front_cpp_liveshot \
    libchromatix_hi846_tsp_front_cpp_preview \
    libchromatix_hi846_tsp_front_cpp_snapshot \
    libchromatix_hi846_tsp_front_cpp_us_chromatix \
    libchromatix_hi846_tsp_front_cpp_video \
    libchromatix_hi846_tsp_front_default_video \
    libchromatix_hi846_tsp_front_eis_video \
    libchromatix_hi846_tsp_front_hfr_120 \
    libchromatix_hi846_tsp_front_hfr_60 \
    libchromatix_hi846_tsp_front_hfr_90 \
    libchromatix_hi846_tsp_front_liveshot \
    libchromatix_hi846_tsp_front_postproc \
    libchromatix_hi846_tsp_front_preview \
    libchromatix_hi846_tsp_front_snapshot \
    libchromatix_hi846_tsp_front_zsl_preview \
    libchromatix_hi846_tsp_front_zsl_video \
    libchromatix_ov13855_chicony_rear_common \
    libchromatix_ov13855_chicony_rear_cpp_ds_chromatix \
    libchromatix_ov13855_chicony_rear_cpp_hfr_120 \
    libchromatix_ov13855_chicony_rear_cpp_hfr_60 \
    libchromatix_ov13855_chicony_rear_cpp_hfr_90 \
    libchromatix_ov13855_chicony_rear_cpp_liveshot \
    libchromatix_ov13855_chicony_rear_cpp_preview \
    libchromatix_ov13855_chicony_rear_cpp_snapshot \
    libchromatix_ov13855_chicony_rear_cpp_us_chromatix \
    libchromatix_ov13855_chicony_rear_cpp_video \
    libchromatix_ov13855_chicony_rear_cpp_video_full \
    libchromatix_ov13855_chicony_rear_default_preview_bu64297 \
    libchromatix_ov13855_chicony_rear_default_video \
    libchromatix_ov13855_chicony_rear_default_video_bu64297 \
    libchromatix_ov13855_chicony_rear_hfr_120 \
    libchromatix_ov13855_chicony_rear_hfr_120_bu64297 \
    libchromatix_ov13855_chicony_rear_hfr_60 \
    libchromatix_ov13855_chicony_rear_hfr_60_bu64297 \
    libchromatix_ov13855_chicony_rear_hfr_90 \
    libchromatix_ov13855_chicony_rear_hfr_90_bu64297 \
    libchromatix_ov13855_chicony_rear_postproc \
    libchromatix_ov13855_chicony_rear_preview \
    libchromatix_ov13855_chicony_rear_snapshot \
    libchromatix_ov13855_chicony_rear_video_full \
    libchromatix_ov13855_chicony_rear_zsl_preview_bu64297 \
    libchromatix_ov13855_chicony_rear_zsl_video_bu64297 \
    libchromatix_ov13855_holitech_13m_common \
    libchromatix_ov13855_holitech_13m_cpp_ds_chromatix \
    libchromatix_ov13855_holitech_13m_cpp_hfr_120 \
    libchromatix_ov13855_holitech_13m_cpp_hfr_60 \
    libchromatix_ov13855_holitech_13m_cpp_hfr_90 \
    libchromatix_ov13855_holitech_13m_cpp_liveshot \
    libchromatix_ov13855_holitech_13m_cpp_preview \
    libchromatix_ov13855_holitech_13m_cpp_snapshot \
    libchromatix_ov13855_holitech_13m_cpp_us_chromatix \
    libchromatix_ov13855_holitech_13m_cpp_video \
    libchromatix_ov13855_holitech_13m_cpp_video_full \
    libchromatix_ov13855_holitech_13m_default_preview_bu64297 \
    libchromatix_ov13855_holitech_13m_default_video \
    libchromatix_ov13855_holitech_13m_default_video_bu64297 \
    libchromatix_ov13855_holitech_13m_eis_video_bu64297 \
    libchromatix_ov13855_holitech_13m_hdr \
    libchromatix_ov13855_holitech_13m_hdr_3a \
    libchromatix_ov13855_holitech_13m_hdr_cpp \
    libchromatix_ov13855_holitech_13m_hfr_120 \
    libchromatix_ov13855_holitech_13m_hfr_120_bu64297 \
    libchromatix_ov13855_holitech_13m_hfr_60 \
    libchromatix_ov13855_holitech_13m_hfr_60_bu64297 \
    libchromatix_ov13855_holitech_13m_hfr_90 \
    libchromatix_ov13855_holitech_13m_hfr_90_bu64297 \
    libchromatix_ov13855_holitech_13m_postproc \
    libchromatix_ov13855_holitech_13m_preview \
    libchromatix_ov13855_holitech_13m_snapshot \
    libchromatix_ov13855_holitech_13m_video_full \
    libchromatix_ov13855_holitech_13m_zsl_preview_bu64297 \
    libchromatix_ov13855_holitech_13m_zsl_video_bu64297 \
    libchromatix_ov16880_qtech_front_common \
    libchromatix_ov16880_qtech_front_cpp_ds_chromatix \
    libchromatix_ov16880_qtech_front_cpp_hfr_120 \
    libchromatix_ov16880_qtech_front_cpp_hfr_60 \
    libchromatix_ov16880_qtech_front_cpp_hfr_90 \
    libchromatix_ov16880_qtech_front_cpp_liveshot \
    libchromatix_ov16880_qtech_front_cpp_preview \
    libchromatix_ov16880_qtech_front_cpp_snapshot \
    libchromatix_ov16880_qtech_front_cpp_us_chromatix \
    libchromatix_ov16880_qtech_front_cpp_video \
    libchromatix_ov16880_qtech_front_cpp_video_full \
    libchromatix_ov16880_qtech_front_default_preview_bu64297 \
    libchromatix_ov16880_qtech_front_default_video \
    libchromatix_ov16880_qtech_front_default_video_bu64297 \
    libchromatix_ov16880_qtech_front_eis_video_bu64297 \
    libchromatix_ov16880_qtech_front_hfr_120 \
    libchromatix_ov16880_qtech_front_hfr_120_bu64297 \
    libchromatix_ov16880_qtech_front_hfr_60 \
    libchromatix_ov16880_qtech_front_hfr_60_bu64297 \
    libchromatix_ov16880_qtech_front_hfr_90 \
    libchromatix_ov16880_qtech_front_hfr_90_bu64297 \
    libchromatix_ov16880_qtech_front_postproc \
    libchromatix_ov16880_qtech_front_preview \
    libchromatix_ov16880_qtech_front_snapshot \
    libchromatix_ov16880_qtech_front_video_full \
    libchromatix_ov16880_qtech_front_zsl_preview_bu64297 \
    libchromatix_ov16880_qtech_front_zsl_video_bu64297 \
    libchromatix_ov16885_holitech_16m_common \
    libchromatix_ov16885_holitech_16m_cpp_ds_chromatix \
    libchromatix_ov16885_holitech_16m_cpp_hfr_120 \
    libchromatix_ov16885_holitech_16m_cpp_hfr_60 \
    libchromatix_ov16885_holitech_16m_cpp_hfr_90 \
    libchromatix_ov16885_holitech_16m_cpp_liveshot \
    libchromatix_ov16885_holitech_16m_cpp_preview \
    libchromatix_ov16885_holitech_16m_cpp_snapshot \
    libchromatix_ov16885_holitech_16m_cpp_us_chromatix \
    libchromatix_ov16885_holitech_16m_cpp_video \
    libchromatix_ov16885_holitech_16m_cpp_video_full \
    libchromatix_ov16885_holitech_16m_default_preview_bu64297 \
    libchromatix_ov16885_holitech_16m_default_video \
    libchromatix_ov16885_holitech_16m_default_video_bu64297 \
    libchromatix_ov16885_holitech_16m_eis_video_bu64297 \
    libchromatix_ov16885_holitech_16m_hdr \
    libchromatix_ov16885_holitech_16m_hdr_3a \
    libchromatix_ov16885_holitech_16m_hdr_cpp \
    libchromatix_ov16885_holitech_16m_hfr_120 \
    libchromatix_ov16885_holitech_16m_hfr_120_bu64297 \
    libchromatix_ov16885_holitech_16m_hfr_60 \
    libchromatix_ov16885_holitech_16m_hfr_60_bu64297 \
    libchromatix_ov16885_holitech_16m_hfr_90 \
    libchromatix_ov16885_holitech_16m_hfr_90_bu64297 \
    libchromatix_ov16885_holitech_16m_postproc \
    libchromatix_ov16885_holitech_16m_preview \
    libchromatix_ov16885_holitech_16m_snapshot \
    libchromatix_ov16885_holitech_16m_video_full \
    libchromatix_ov16885_holitech_16m_zsl_preview_bu64297 \
    libchromatix_ov16885_holitech_16m_zsl_video_bu64297 \
    libchromatix_ov16885_ofilm_16m_common \
    libchromatix_ov16885_ofilm_16m_cpp_ds_chromatix \
    libchromatix_ov16885_ofilm_16m_cpp_hfr_120 \
    libchromatix_ov16885_ofilm_16m_cpp_hfr_60 \
    libchromatix_ov16885_ofilm_16m_cpp_hfr_90 \
    libchromatix_ov16885_ofilm_16m_cpp_liveshot \
    libchromatix_ov16885_ofilm_16m_cpp_preview \
    libchromatix_ov16885_ofilm_16m_cpp_snapshot \
    libchromatix_ov16885_ofilm_16m_cpp_us_chromatix \
    libchromatix_ov16885_ofilm_16m_cpp_video \
    libchromatix_ov16885_ofilm_16m_cpp_video_full \
    libchromatix_ov16885_ofilm_16m_default_preview_bu64297 \
    libchromatix_ov16885_ofilm_16m_default_video \
    libchromatix_ov16885_ofilm_16m_default_video_bu64297 \
    libchromatix_ov16885_ofilm_16m_eis_video_bu64297 \
    libchromatix_ov16885_ofilm_16m_hdr \
    libchromatix_ov16885_ofilm_16m_hdr_3a \
    libchromatix_ov16885_ofilm_16m_hdr_cpp \
    libchromatix_ov16885_ofilm_16m_hfr_120 \
    libchromatix_ov16885_ofilm_16m_hfr_120_bu64297 \
    libchromatix_ov16885_ofilm_16m_hfr_60 \
    libchromatix_ov16885_ofilm_16m_hfr_60_bu64297 \
    libchromatix_ov16885_ofilm_16m_hfr_90 \
    libchromatix_ov16885_ofilm_16m_hfr_90_bu64297 \
    libchromatix_ov16885_ofilm_16m_postproc \
    libchromatix_ov16885_ofilm_16m_preview \
    libchromatix_ov16885_ofilm_16m_snapshot \
    libchromatix_ov16885_ofilm_16m_video_full \
    libchromatix_ov16885_ofilm_16m_zsl_preview_bu64297 \
    libchromatix_ov16885_ofilm_16m_zsl_video_bu64297 \
    libchromatix_ov8856_chicony_front_a3_default_preview \
    libchromatix_ov8856_chicony_front_a3_default_video \
    libchromatix_ov8856_chicony_front_a3_hfr_120 \
    libchromatix_ov8856_chicony_front_a3_hfr_60 \
    libchromatix_ov8856_chicony_front_a3_hfr_90 \
    libchromatix_ov8856_chicony_front_common \
    libchromatix_ov8856_chicony_front_cpp_ds_chromatix \
    libchromatix_ov8856_chicony_front_cpp_hfr_120 \
    libchromatix_ov8856_chicony_front_cpp_hfr_60 \
    libchromatix_ov8856_chicony_front_cpp_hfr_90 \
    libchromatix_ov8856_chicony_front_cpp_liveshot \
    libchromatix_ov8856_chicony_front_cpp_preview \
    libchromatix_ov8856_chicony_front_cpp_snapshot \
    libchromatix_ov8856_chicony_front_cpp_us_chromatix \
    libchromatix_ov8856_chicony_front_cpp_video \
    libchromatix_ov8856_chicony_front_default_video \
    libchromatix_ov8856_chicony_front_eis_video \
    libchromatix_ov8856_chicony_front_hfr_120 \
    libchromatix_ov8856_chicony_front_hfr_60 \
    libchromatix_ov8856_chicony_front_hfr_90 \
    libchromatix_ov8856_chicony_front_liveshot \
    libchromatix_ov8856_chicony_front_postproc \
    libchromatix_ov8856_chicony_front_preview \
    libchromatix_ov8856_chicony_front_snapshot \
    libchromatix_ov8856_chicony_front_zsl_preview \
    libchromatix_ov8856_chicony_front_zsl_video \
    libdepthcomputation \
    libdepthmapwrapper \
    libeepromcutter \
    libflash_pmic \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_bokeh \
    libmmcamera_dbg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_gc5025_ofilm_13m \
    libmmcamera_gc5025_ofilm_13m_fm24c64d_eeprom \
    libmmcamera_gc5025_ofilm_16m \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hi1333_ofilm_13m \
    libmmcamera_hi1333_ofilm_13m_fm24c64d_eeprom \
    libmmcamera_hi556_holitech_13m \
    libmmcamera_hi556_holitech_13m_fm24c64d_eeprom \
    libmmcamera_hi556_holitech_16m \
    libmmcamera_hi846_kingcome_front \
    libmmcamera_hi846_tsp_front \
    libmmcamera_hi846_tsp_front_eeprom \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_irs2877_polar_eeprom \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_ov13855_chicony_rear \
    libmmcamera_ov13855_chicony_rear_fm24c64d_eeprom \
    libmmcamera_ov13855_holitech_13m \
    libmmcamera_ov13855_holitech_13m_fm24c64d_eeprom \
    libmmcamera_ov16880_qtech_front \
    libmmcamera_ov16880_qtech_front_fm24c64d_eeprom \
    libmmcamera_ov16880_qtech_rear \
    libmmcamera_ov16885_holitech_16m \
    libmmcamera_ov16885_holitech_16m_fm24c64d_eeprom \
    libmmcamera_ov16885_ofilm_16m \
    libmmcamera_ov16885_ofilm_16m_fm24c64d_eeprom \
    libmmcamera_ov8856 \
    libmmcamera_ov8856_2lane \
    libmmcamera_ov8856_4lane \
    libmmcamera_ov8856_chicony_front \
    libmmcamera_ov8856_chicony_front_eeprom \
    libmmcamera_ov8856b_chicony_front \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_stillmore_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libseemore \
    libspectre \
    cdfinger.fingerprint.default \
    fingerprint.sdm660 \
    libgf_ca \
    libgf_hal \
    libqfp-service \
    libvendor.goodix.hardware.fingerprint@1.0-service \
    libvendor.goodix.hardware.fingerprint@1.0 \
    vendor.qti.hardware.fingerprint-V1.0-java \
    qfp-daemon \
    sensors.qti
