#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/asus/X01BD

PRODUCT_COPY_FILES += \
    vendor/asus/X01BD/proprietary/product/etc/permissions/qti_fingerprint_interface.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/qti_fingerprint_interface.xml \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/NonCE/QRD_NonCE_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/NonCE/QRD_NonCE_Bluetooth_cal.acdb \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/NonCE/QRD_NonCE_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/NonCE/QRD_NonCE_General_cal.acdb \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/NonCE/QRD_NonCE_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/NonCE/QRD_NonCE_Global_cal.acdb \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/NonCE/QRD_NonCE_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/NonCE/QRD_NonCE_Handset_cal.acdb \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/NonCE/QRD_NonCE_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/NonCE/QRD_NonCE_Hdmi_cal.acdb \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/NonCE/QRD_NonCE_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/NonCE/QRD_NonCE_Headset_cal.acdb \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/NonCE/QRD_NonCE_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/NonCE/QRD_NonCE_Speaker_cal.acdb \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/NonCE/QRD_NonCE_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/NonCE/QRD_NonCE_workspaceFile.qwsp \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/QRD/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_workspaceFile.qwsp \
    vendor/asus/X01BD/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/asus/X01BD/proprietary/vendor/etc/camera/ar1337_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ar1337_chromatix.xml \
    vendor/asus/X01BD/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/asus/X01BD/proprietary/vendor/etc/camera/gc5025_ofilm_13m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/gc5025_ofilm_13m_chromatix.xml \
    vendor/asus/X01BD/proprietary/vendor/etc/camera/imx486_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx486_chromatix.xml \
    vendor/asus/X01BD/proprietary/vendor/etc/camera/ov13855_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13855_chromatix.xml \
    vendor/asus/X01BD/proprietary/vendor/etc/camera/s5k5e9yu05_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k5e9yu05_chromatix.xml \
    vendor/asus/X01BD/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/asus/X01BD/proprietary/vendor/firmware/Himax_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Himax_firmware.bin \
    vendor/asus/X01BD/proprietary/vendor/firmware/a512_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b00 \
    vendor/asus/X01BD/proprietary/vendor/firmware/a512_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b01 \
    vendor/asus/X01BD/proprietary/vendor/firmware/a512_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b02 \
    vendor/asus/X01BD/proprietary/vendor/firmware/a512_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.elf \
    vendor/asus/X01BD/proprietary/vendor/firmware/a512_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.mdt \
    vendor/asus/X01BD/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/asus/X01BD/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/asus/X01BD/proprietary/vendor/firmware/a530_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_gpmu.fw2 \
    vendor/asus/X01BD/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/asus/X01BD/proprietary/vendor/firmware/cppf.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b00 \
    vendor/asus/X01BD/proprietary/vendor/firmware/cppf.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b01 \
    vendor/asus/X01BD/proprietary/vendor/firmware/cppf.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b02 \
    vendor/asus/X01BD/proprietary/vendor/firmware/cppf.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b03 \
    vendor/asus/X01BD/proprietary/vendor/firmware/cppf.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b04 \
    vendor/asus/X01BD/proprietary/vendor/firmware/cppf.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b05 \
    vendor/asus/X01BD/proprietary/vendor/firmware/cppf.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b06 \
    vendor/asus/X01BD/proprietary/vendor/firmware/cppf.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b07 \
    vendor/asus/X01BD/proprietary/vendor/firmware/cppf.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.mdt \
    vendor/asus/X01BD/proprietary/vendor/firmware/hx_criteria.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx_criteria.csv \
    vendor/asus/X01BD/proprietary/vendor/firmware/novatek_ts_fw_v8D.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_v8D.bin \
    vendor/asus/X01BD/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/asus/X01BD/proprietary/vendor/firmware/widevine.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b00 \
    vendor/asus/X01BD/proprietary/vendor/firmware/widevine.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b01 \
    vendor/asus/X01BD/proprietary/vendor/firmware/widevine.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b02 \
    vendor/asus/X01BD/proprietary/vendor/firmware/widevine.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b03 \
    vendor/asus/X01BD/proprietary/vendor/firmware/widevine.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b04 \
    vendor/asus/X01BD/proprietary/vendor/firmware/widevine.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b05 \
    vendor/asus/X01BD/proprietary/vendor/firmware/widevine.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b06 \
    vendor/asus/X01BD/proprietary/vendor/firmware/widevine.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b07 \
    vendor/asus/X01BD/proprietary/vendor/firmware/widevine.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.mdt

PRODUCT_PACKAGES += \
    sensors.ssc \
    vendor.qti.hardware.fingerprint@1.0 \
    libactuator_imx486_holitech_12m \
    libchromatix_ar1337_common \
    libchromatix_ar1337_cpp_ds_chromatix \
    libchromatix_ar1337_cpp_hfr_120 \
    libchromatix_ar1337_cpp_hfr_60 \
    libchromatix_ar1337_cpp_hfr_90 \
    libchromatix_ar1337_cpp_liveshot \
    libchromatix_ar1337_cpp_preview \
    libchromatix_ar1337_cpp_snapshot \
    libchromatix_ar1337_cpp_us_chromatix \
    libchromatix_ar1337_cpp_video \
    libchromatix_ar1337_cpp_video_full \
    libchromatix_ar1337_default_preview_bu64297 \
    libchromatix_ar1337_default_video \
    libchromatix_ar1337_default_video_bu64297 \
    libchromatix_ar1337_front_bokeh_cpp_preview \
    libchromatix_ar1337_front_bokeh_cpp_snapshot \
    libchromatix_ar1337_front_bokeh_preview \
    libchromatix_ar1337_front_bokeh_snapshot \
    libchromatix_ar1337_front_bokeh_zsl_preview_bu64297 \
    libchromatix_ar1337_hfr_120 \
    libchromatix_ar1337_hfr_120_bu64297 \
    libchromatix_ar1337_hfr_60 \
    libchromatix_ar1337_hfr_60_bu64297 \
    libchromatix_ar1337_hfr_90 \
    libchromatix_ar1337_hfr_90_bu64297 \
    libchromatix_ar1337_postproc \
    libchromatix_ar1337_preview \
    libchromatix_ar1337_snapshot \
    libchromatix_ar1337_video_full \
    libchromatix_ar1337_zsl_preview_bu64297 \
    libchromatix_ar1337_zsl_video_bu64297 \
    libchromatix_gc5025_ofilm_13m_common \
    libchromatix_gc5025_ofilm_13m_cpp_ds_chromatix \
    libchromatix_gc5025_ofilm_13m_cpp_hfr_120 \
    libchromatix_gc5025_ofilm_13m_cpp_hfr_60 \
    libchromatix_gc5025_ofilm_13m_cpp_hfr_90 \
    libchromatix_gc5025_ofilm_13m_cpp_liveshot \
    libchromatix_gc5025_ofilm_13m_cpp_preview \
    libchromatix_gc5025_ofilm_13m_cpp_snapshot \
    libchromatix_gc5025_ofilm_13m_cpp_us_chromatix \
    libchromatix_gc5025_ofilm_13m_cpp_video \
    libchromatix_gc5025_ofilm_13m_cpp_video_full \
    libchromatix_gc5025_ofilm_13m_default_preview_bu64297 \
    libchromatix_gc5025_ofilm_13m_default_video \
    libchromatix_gc5025_ofilm_13m_default_video_bu64297 \
    libchromatix_gc5025_ofilm_13m_hfr_120 \
    libchromatix_gc5025_ofilm_13m_hfr_120_bu64297 \
    libchromatix_gc5025_ofilm_13m_hfr_60 \
    libchromatix_gc5025_ofilm_13m_hfr_60_bu64297 \
    libchromatix_gc5025_ofilm_13m_hfr_90 \
    libchromatix_gc5025_ofilm_13m_hfr_90_bu64297 \
    libchromatix_gc5025_ofilm_13m_postproc \
    libchromatix_gc5025_ofilm_13m_preview \
    libchromatix_gc5025_ofilm_13m_snapshot \
    libchromatix_gc5025_ofilm_13m_video_full \
    libchromatix_gc5025_ofilm_13m_zsl_preview_bu64297 \
    libchromatix_gc5025_ofilm_13m_zsl_video_bu64297 \
    libchromatix_imx486_bokenh \
    libchromatix_imx486_bokenh_video_3a \
    libchromatix_imx486_common \
    libchromatix_imx486_cpp_bokenh_snapshot \
    libchromatix_imx486_cpp_hfr_120 \
    libchromatix_imx486_cpp_hfr_60 \
    libchromatix_imx486_cpp_hfr_90 \
    libchromatix_imx486_cpp_liveshot \
    libchromatix_imx486_cpp_preview \
    libchromatix_imx486_cpp_snapshot \
    libchromatix_imx486_cpp_video \
    libchromatix_imx486_default_preview_3a \
    libchromatix_imx486_default_video \
    libchromatix_imx486_default_video_3a \
    libchromatix_imx486_hdr \
    libchromatix_imx486_hdr_cpp \
    libchromatix_imx486_hdr_video_3a \
    libchromatix_imx486_hfr_120 \
    libchromatix_imx486_hfr_120_3a \
    libchromatix_imx486_hfr_60 \
    libchromatix_imx486_hfr_60_3a \
    libchromatix_imx486_hfr_90 \
    libchromatix_imx486_hfr_90_3a \
    libchromatix_imx486_liveshot \
    libchromatix_imx486_postproc \
    libchromatix_imx486_preview \
    libchromatix_imx486_snapshot \
    libchromatix_imx486_zsl_preview_3a \
    libchromatix_imx486_zsl_video_3a \
    libchromatix_ov13855_bokeh \
    libchromatix_ov13855_bokeh_bu64297 \
    libchromatix_ov13855_common \
    libchromatix_ov13855_cpp_bokeh \
    libchromatix_ov13855_cpp_ds_chromatix \
    libchromatix_ov13855_cpp_hfr_120 \
    libchromatix_ov13855_cpp_hfr_60 \
    libchromatix_ov13855_cpp_hfr_90 \
    libchromatix_ov13855_cpp_liveshot \
    libchromatix_ov13855_cpp_preview \
    libchromatix_ov13855_cpp_snapshot \
    libchromatix_ov13855_cpp_us_chromatix \
    libchromatix_ov13855_cpp_video \
    libchromatix_ov13855_cpp_video_full \
    libchromatix_ov13855_default_preview_bu64297 \
    libchromatix_ov13855_default_video \
    libchromatix_ov13855_default_video_bu64297 \
    libchromatix_ov13855_hfr_120 \
    libchromatix_ov13855_hfr_120_bu64297 \
    libchromatix_ov13855_hfr_60 \
    libchromatix_ov13855_hfr_60_bu64297 \
    libchromatix_ov13855_hfr_90 \
    libchromatix_ov13855_hfr_90_bu64297 \
    libchromatix_ov13855_postproc \
    libchromatix_ov13855_preview \
    libchromatix_ov13855_snapshot \
    libchromatix_ov13855_video_full \
    libchromatix_ov13855_zsl_preview_bu64297 \
    libchromatix_ov13855_zsl_video_bu64297 \
    libchromatix_s5k5e9yu05_common \
    libchromatix_s5k5e9yu05_cpp_hfr_120 \
    libchromatix_s5k5e9yu05_cpp_hfr_60 \
    libchromatix_s5k5e9yu05_cpp_hfr_90 \
    libchromatix_s5k5e9yu05_cpp_liveshot \
    libchromatix_s5k5e9yu05_cpp_preview \
    libchromatix_s5k5e9yu05_cpp_snapshot \
    libchromatix_s5k5e9yu05_cpp_video \
    libchromatix_s5k5e9yu05_default_preview_3a \
    libchromatix_s5k5e9yu05_default_video \
    libchromatix_s5k5e9yu05_default_video_3a \
    libchromatix_s5k5e9yu05_hfr_120 \
    libchromatix_s5k5e9yu05_hfr_120_3a \
    libchromatix_s5k5e9yu05_hfr_60 \
    libchromatix_s5k5e9yu05_hfr_60_3a \
    libchromatix_s5k5e9yu05_hfr_90 \
    libchromatix_s5k5e9yu05_hfr_90_3a \
    libchromatix_s5k5e9yu05_postproc \
    libchromatix_s5k5e9yu05_preview \
    libchromatix_s5k5e9yu05_snapshot \
    libchromatix_s5k5e9yu05_zsl_preview_3a \
    libchromatix_s5k5e9yu05_zsl_video_3a \
    libdepthmapwrapper \
    libflash_pmic \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_ar1337 \
    libmmcamera_ar1337_eeprom \
    libmmcamera_bokeh \
    libmmcamera_dbg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_gc5025 \
    libmmcamera_gc5025_ofilm_13m \
    libmmcamera_gc5025_ofilm_13m_fm24c64d_eeprom \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_imx486 \
    libmmcamera_imx486_eeprom \
    libmmcamera_irs1645 \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_ov13855 \
    libmmcamera_ov13855_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k5e9_slave_back_p24c64e_eeprom \
    libmmcamera_s5k5e9yu05 \
    libmmcamera_stillmore_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libseemore \
    cdfinger.fingerprint.default \
    fingerprint.focaltech.default \
    vendor.qti.hardware.fingerprint-V1.0-java \
    sensors.qti
